use PIN instead of hash
sim590/dpaste pull request #1
Opened 2016-11-21 23:01 UTC by aberaud

A human can manually copy a PIN, not a hash.

2016-11-22 18:46 UTC, sim590 commented
Cool! A first PR! :smile:

2016-11-22 19:11 UTC, sim590 requested changes
Thanks for the PR! I think that your changes must have break `pasted` component (`src/pasted.cpp`, `src/server.cpp`) since you changed the `Node` functions signatures.

2016-11-22 19:11 UTC, sim590 commented on src/dpaste.cpp
> -        return 0;
Why does this patch disable `dpaste -v`? May be, your CMake solution should provide equivalent macros found in `config.h` autoconf?

2016-11-22 19:11 UTC, sim590 commented on src/dpaste.cpp
> -#include "config.h"
I understad that you removed this line since it doesn't make sense when using CMake. I do use "config.h" which is generated by autoconf and contains macros such as `VERSION` and `PACKAGE`. The proper way to handle this would be:
```cpp
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif
```

Your change makes me think that I have to use the macro `PACKAGE` in the output of `dpaste -h`.

2016-11-22 19:11 UTC, sim590 commented on src/node.cpp
> +    rand_.seed(seed);
Oh. I think I forgot to seed in my first implementation. hehe

2016-11-22 19:11 UTC, sim590 commented on src/node.cpp
> +        bool done {false};
Do we really need that `bool` value? Wasn't the use of `cv->wait(lk);` enough?

2016-11-22 19:11 UTC, sim590 commented on src/node.cpp
> -	v->id = vid_dist(rand_);
Oh. Okay, I just saw that from OpenDHT:
```cpp
    if (val->id == Value::INVALID_ID) {
        crypto::random_device rdev;
        std::uniform_int_distribution<Value::Id> rand_id {};
        val->id = rand_id(rdev);
    }
```
For now, I guess it's fine if we don't have use of knowing the value id. However, if we would implement functionnalities based on PHT indexation, we'd need the value id.

2016-11-22 19:14 UTC, aberaud commented on src/node.cpp
> +        bool done {false};
As per the standard: "wait causes the current thread to block until the condition variable is notified or a spurious wakeup occurs". Spurious wakeup can occur even without any call to notify.

2016-11-22 19:16 UTC, aberaud commented on src/node.cpp
> -	v->id = vid_dist(rand_);
If we use PHT at some point, the PHT code will then abstract handling the value ID.

2016-11-22 19:17 UTC, aberaud commented on src/dpaste.cpp
> -#include "config.h"
yes this was a first iteration to get stuff working

2016-11-22 19:33 UTC, sim590 commented on src/node.cpp
> +        bool done {false};
Oh! I didn't know!

2017-01-03 13:39 UTC, sim590 requested changes
Requesting really minor text replace before I merge it.

Ping me after this and I'll merge!

2017-01-03 13:39 UTC, sim590 commented on src/node.h
> +     * @param hash  The hash to lookup.
s/hash/code/g

2017-01-03 13:39 UTC, sim590 commented on src/ipc.cpp
> +        code = h->as<std::string>();
Use `c` instead of `h` here.

2017-01-03 16:01 UTC, merged